server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Pass@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: abhipawar762@gmail.com
    password: qbwc mvde yqjz znag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: servicehub-auth-secret-key-256-bit-long!!
